export * from './anime-card/anime-card.component'
export * from './general/footer/footer.component'
export * from './general/header/header.component'
export * from './pages/page-home/page-home.component'
export * from './pages/page-not-found/page-not-found.component'